# Generated by Django 5.0 on 2024-02-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='uuid',
        ),
    ]
