# Generated by Django 5.0 on 2024-01-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_user_order_customer_and_more'),
        ('shop', '0002_category_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='product',
        ),
    ]
