# Generated by Django 5.0.2 on 2024-04-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='product_cat_name_4f76a1_idx',
        ),
    ]
