# Generated by Django 5.0.2 on 2024-02-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percent',
            new_name='discount',
        ),
    ]
