# Generated by Django 5.0 on 2024-01-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='book',
            new_name='product',
        ),
    ]
