# Generated by Django 5.0 on 2024-02-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_id_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='uuid',
        ),
    ]
