# Generated by Django 5.0 on 2024-02-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author_id',
            new_name='author',
        ),
    ]
