# Generated by Django 5.0 on 2024-02-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_author_id_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='uuid',
        ),
    ]
