# Generated by Django 5.0 on 2024-02-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_author_uuid_remove_category_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
